#pragma once

#include <random>
#include <list>
#include <queue>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <iostream>
#include <string>
#include <limits>
#include <fstream>
#include <codecvt>
#include <functional>

#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>

#include "Defines.h"
#include "Variables.h"
#include "Utils.h"
#include "Singleton.h"
#include "TimeMgr.h"
#include "GameObject.h"
#include "DataTable.h"
#include "StringTable.h"
#include "TileTable.h"
#include "DataTableMgr.h"
#include "Framework.h"
#include "InputMgr.h"
#include "Animator.h"
#include "AnimationClip.h"
#include "ResourceMgr.h"
#include "TextGo.h"
#include "SpriteGo.h"
#include "SceneMgr.h"
#include "Scene.h"
#include "ObjectPool.h"
#include "SoundMgr.h"
#include "SaveMgr.h"
#include "ViewMgr.h"